name: frontend app

on:
  push:
    branches: [ "main" ]

jobs:
    
    deploy_frontend_app:

        name: deploy app
        runs-on: ubuntu-latest

        # steps:

        #     - name: checkout frontend dir as root dir
        #       uses: actions/checkout@v3

        #     - name: login aws
        #       run: |
        #         ls -l
                 
        #     - name: install node js
        #       uses: actions/setup-node@v3
        #       with:
        #         node-version: 18.x
            
        #     - name: install packages and build app
        #       run: |
        #         npm ci
        #         npm run build
        #         ls -l

        steps:
            - name: Connect to EC2 instance
              uses: easingthemes/ssh-deploy@main
              with:
                REMOTE_HOST: ${{ secrets.EC2_HOST }}
                REMOTE_USER: ${{ secrets.EC2_USERNAME }}
                SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
                SCRIPT_AFTER: |
                    sudo yum install -y docker
                    sudo docker run -d -p 3000:3000 ${{ secrets.DOCKERUSER }}/frontend_app:v5



         