name: frontend app

on:
  push:
    branches: [ "main" ]

jobs:
    
    deploy_frontend_app:

        name: deploy app
        runs-on: ubuntu-latest


        steps:
          # - name: connect to ec2
          #   run: |
          #     ssh -i /home/srinp/my-first-pem.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}
          #     docker run -d -p 3000:80 ${{ secrets.DOCKER_USERNAME }}/frontend_app:v5

            - name: Connect to EC2 instance
              uses: easingthemes/ssh-deploy@main
              with:
                REMOTE_HOST: ${{ secrets.EC2_HOST }}
                REMOTE_USER: ${{ secrets.EC2_USERNAME }}
                SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
                SCRIPT_AFTER: |
                  docker run -d -p 3000:80 ${{ secrets.DOCKER_USERNAME }}/frontend_app:v5

        