name: build counter app

on:
  push:
    branches: [ "main" ]

jobs:

  build_deploy_app:

    runs-on: ubuntu-latest

    steps:

      - name: checking out repo
        uses: actions/checkout@v3

      - name: installing node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      
      - name: install packages and build react app
        run: |
          npm ci
          npm run build

      - name: login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ secrets.GIT_USERNAME }}/frontend_app:v${{ github.run_number }}

      - name: connect EC2 using SSH
        run: |
          echo "${{secrets.EC2_PRIVATE_KEY}}" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} '

            docker login ghcr.io -u ${{ secrets.GIT_USERNAME }} -p ${{ secrets.GIT_TOKEN }}
            docker stop $(sudo docker ps -aq)
            docker run -d -p 3000:80 ghcr.io/${{ secrets.GIT_USERNAME }}/frontend_app:v${{github.run_number}}
            '
          rm private_key

      # - name: Connect to EC2 instance
      #   uses: easingthemes/ssh-deploy@main
      #   with:
      #       REMOTE_HOST: ${{ secrets.EC2_HOST }}
      #       REMOTE_USER: ${{ secrets.EC2_USERNAME }}
      #       SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
      #       EXCLUDE: '**'
      #       SCRIPT_AFTER: |
      #         echo ${{ secrets.GIT_TOKEN }} | docker login ghcr.io -u ${{ secrets.GIT_USERNAME }} --password-stdin
      #         docker stop $(sudo docker ps -aq)
      #         docker pull ghcr.io/${{ secrets.GIT_USERNAME }}/frontend_app:v1
      #         docker run -d -p 3000:80 ghcr.io/${{ secrets.GIT_USERNAME }}/frontend_app:v1