name: build counter app

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install node js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      
      - name: install packages
        run: npm ci

      - name: build app
        run: npm run build

      - name: build image
        run: docker build -t multistagecounter -f multistage.Dockerfile .

      - name: login docker
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKER_PASS }}
        
      - name: push to docker hub
        run: docker push multistagecounter 